spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
        - id: last-word-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/last-word/**
        - id: user-profile-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/user-profile/**

server:
  port: 8080